/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/bootstrap": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Bootstrap */
        get: operations["get_bootstrap_api_bootstrap_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/calculate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Calculate */
        post: operations["post_calculate_api_calculate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/speed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Speed */
        post: operations["post_speed_api_speed_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/calculate/batch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Calculate Batch */
        post: operations["post_calculate_batch_api_calculate_batch_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/teams": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Teams */
        get: operations["get_teams_api_teams_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/teams/{team_name}/presets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Put Preset */
        put: operations["put_preset_api_teams__team_name__presets_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/teams/{team_name}/presets/{index}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Preset Route */
        delete: operations["delete_preset_route_api_teams__team_name__presets__index__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/teams/{team_name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Team Route */
        delete: operations["delete_team_route_api_teams__team_name__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AbilityOut */
        AbilityOut: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
        };
        /** BatchCalculateRequest */
        BatchCalculateRequest: {
            attacker: components["schemas"]["MonBuildIn"];
            defender: components["schemas"]["MonBuildIn"];
            /** Move Names */
            move_names: string[];
            field?: components["schemas"]["FieldIn"];
        };
        /** BatchCalculateResponse */
        BatchCalculateResponse: {
            /** Rows */
            rows: components["schemas"]["MoveSummaryRow"][];
        };
        /** BootstrapResponse */
        BootstrapResponse: {
            /** Species */
            species: components["schemas"]["SpeciesOut"][];
            /** Moves */
            moves: components["schemas"]["MoveOut"][];
            /** Items */
            items: components["schemas"]["ItemOut"][];
            /** Abilities */
            abilities: components["schemas"]["AbilityOut"][];
            /** Natures */
            natures: components["schemas"]["NatureOut"][];
            /** Regulations */
            regulations: string[];
            /** Sp Budget */
            sp_budget: number;
            /** Sp Max */
            sp_max: number;
            /** Weathers */
            weathers: string[];
            /** Terrains */
            terrains: string[];
            /** Statuses */
            statuses: string[];
            /** Type Chart */
            type_chart: {
                [key: string]: {
                    [key: string]: number;
                };
            };
        };
        /** CalculateRequest */
        CalculateRequest: {
            attacker: components["schemas"]["MonBuildIn"];
            defender: components["schemas"]["MonBuildIn"];
            /** Move Name */
            move_name: string;
            field?: components["schemas"]["FieldIn"];
        };
        /** CalculateResponse */
        CalculateResponse: {
            /** Rolls */
            rolls: number[];
            /** Attacker Speed */
            attacker_speed: number;
            /** Defender Speed */
            defender_speed: number;
            /** Defender Max Hp */
            defender_max_hp: number;
            /** Ko Chances */
            ko_chances: components["schemas"]["KoChanceEntry"][];
        };
        /** FieldIn */
        FieldIn: {
            /**
             * Game Type
             * @default Singles
             */
            game_type: string;
            /** Weather */
            weather?: string | null;
            /** Terrain */
            terrain?: string | null;
            /**
             * Is Gravity
             * @default false
             */
            is_gravity: boolean;
            attacker_side?: components["schemas"]["SideIn"];
            defender_side?: components["schemas"]["SideIn"];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ItemOut */
        ItemOut: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Is Mega Stone */
            is_mega_stone: boolean;
            /** Is Berry */
            is_berry: boolean;
            /** Legal In Reg M A */
            legal_in_reg_m_a: boolean;
        };
        /** KoChanceEntry */
        KoChanceEntry: {
            /** Hits */
            hits: number;
            /** Probability */
            probability: number;
        };
        /** MonBuildIn */
        MonBuildIn: {
            /** Species */
            species: string;
            /** Ability */
            ability?: string | null;
            /** Item */
            item?: string | null;
            /** Nature */
            nature?: string | null;
            /** Sp */
            sp?: {
                [key: string]: number;
            };
            /** Boosts */
            boosts?: {
                [key: string]: number;
            };
            /** Status */
            status?: string | null;
            /**
             * Current Hp Fraction
             * @default 1
             */
            current_hp_fraction: number;
        };
        /** MoveOut */
        MoveOut: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Type */
            type: string;
            /** Category */
            category: string;
            /** Base Power */
            base_power: number;
            /** Priority */
            priority: number;
            /** Target */
            target: string;
            /** Flags */
            flags: {
                [key: string]: number;
            };
            /** Multihit */
            multihit?: number[] | null;
            /** Has Secondary */
            has_secondary: boolean;
            /** Drain */
            drain?: number[] | null;
            /** Recoil */
            recoil: number;
            /** Breaks Protect */
            breaks_protect: boolean;
            /** Will Crit */
            will_crit: boolean;
            /** Crit Ratio */
            crit_ratio: number;
            /** Description */
            description?: string | null;
            /** Is Status */
            is_status: boolean;
            /** Is Spread */
            is_spread: boolean;
        };
        /** MoveSummaryRow */
        MoveSummaryRow: {
            /** Move */
            move: string;
            /** Type */
            type: string;
            /** Category */
            category: string;
            /** Base Power */
            base_power: number;
            /** Avg Damage Pct */
            avg_damage_pct: number;
            /** Ko Chances */
            ko_chances: components["schemas"]["KoChanceEntry"][];
        };
        /** NatureOut */
        NatureOut: {
            /** Name */
            name: string;
            /** Plus */
            plus?: string | null;
            /** Minus */
            minus?: string | null;
            /** Is Neutral */
            is_neutral: boolean;
        };
        /** PresetIn */
        PresetIn: {
            /** Label */
            label: string;
            /** Species */
            species: string;
            /** Nature */
            nature: string;
            /** Ability */
            ability: string;
            /** Item */
            item?: string | null;
            /** Sp */
            sp?: {
                [key: string]: number;
            };
        };
        /** SideIn */
        SideIn: {
            /** Side Conditions */
            side_conditions?: string[];
            /**
             * Is Protected
             * @default false
             */
            is_protected: boolean;
            /**
             * Is Helping Hand
             * @default false
             */
            is_helping_hand: boolean;
        };
        /** SpeciesOut */
        SpeciesOut: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Types */
            types: string[];
            /** Base Stats */
            base_stats: {
                [key: string]: number;
            };
            /** Ability */
            ability: string;
            /** Weight Kg */
            weight_kg: number;
            /** Base Species */
            base_species?: string | null;
            /** Is Mega */
            is_mega: boolean;
            /** Sprite Url */
            sprite_url?: string | null;
            /** Ability Slots */
            ability_slots: string[];
            /** Learnable Moves */
            learnable_moves: string[];
            /** Mega Stone */
            mega_stone?: string | null;
            /** Suggested Nature */
            suggested_nature: string;
            /** Suggested Sp */
            suggested_sp: {
                [key: string]: number;
            };
            /** Suggested Item */
            suggested_item?: string | null;
        };
        /** SpeedRequest */
        SpeedRequest: {
            attacker: components["schemas"]["MonBuildIn"];
            defender: components["schemas"]["MonBuildIn"];
            field?: components["schemas"]["FieldIn"];
        };
        /** SpeedResponse */
        SpeedResponse: {
            /** Attacker Speed */
            attacker_speed: number;
            /** Defender Speed */
            defender_speed: number;
        };
        /** TeamsResponse */
        TeamsResponse: {
            /** Teams */
            teams: {
                [key: string]: components["schemas"]["PresetIn"][];
            };
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_bootstrap_api_bootstrap_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BootstrapResponse"];
                };
            };
        };
    };
    post_calculate_api_calculate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CalculateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CalculateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_speed_api_speed_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SpeedRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpeedResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_calculate_batch_api_calculate_batch_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BatchCalculateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BatchCalculateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_teams_api_teams_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamsResponse"];
                };
            };
        };
    };
    put_preset_api_teams__team_name__presets_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                team_name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PresetIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_preset_route_api_teams__team_name__presets__index__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                team_name: string;
                index: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_team_route_api_teams__team_name__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                team_name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
